# Generated by Django 2.2 on 2020-06-29 18:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0006_workflow_other_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareWorkflowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_owner', to=settings.AUTH_USER_MODEL)),
                ('person_sharing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person_who_shared_the_workflow', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person_who_received', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow')),
            ],
        ),
    ]
