# Generated by Django 2.2 on 2020-06-29 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share_workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareworkflowmodel',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='person_sharing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shareworkflowmodel',
            name='person_sharing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='real_person_sharing', to=settings.AUTH_USER_MODEL),
        ),
    ]
