# Generated by Django 2.2 on 2020-06-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image_path',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
