# Generated by Django 2.2 on 2020-06-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200630_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image_path',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/storage/no-profile-image.PNG', max_length=100, null=True),
        ),
    ]
