# Generated by Django 2.2 on 2020-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('starred', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
