# Generated by Django 2.2 on 2020-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflow_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
