# Generated by Django 2.2 on 2020-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflow_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='title',
            field=models.TextField(default='Create title', null=True),
        ),
    ]
