# Generated by Django 2.2 on 2020-06-29 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflows', '0005_auto_20200622_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='other_users',
            field=models.ManyToManyField(related_name='users_shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
